'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mod = require('../index');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('hello', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('response', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      //console.log(response);

      expect(response).to.not.be.empty;
      expect(response).to.have.property('statusCode');
      expect(response).to.have.property('body');
      expect(response.statusCode).to.equal(200);
      expect(body).to.have.property('message');
      expect(body).to.have.property('input');
      expect(body.message).to.equal('Go Serverless v1.0! Your function executed successfully!');
    });
  });
});
