'use strict';

exports.handler = (event, context, callback) => {
  /*
   * Extract request object in order to preserve httpVersion field.
   * This is necessary in order to match the client's httpVersion. Please
   * refer to your CloudFront Distribution's HttpVersion configuration for whether to
   * specify HTTP 1.1, 2.0 or match-viewer.
   */
  const request = event.Records[0].cf.request;

  /*
   * Generate HTTP response using 200 status code with a simple body.
   */
  const response = {
    status: '200',
    statusDescription: 'HTTP OK',
    httpVersion: request.httpVersion,
    body: 'Example body generated by Lambda@Edge function.',
    headers: {
      Vary: ['*'],
      'Last-Modified': ['2017-01-13'],
    },
  };

  callback(null, response);
};
